name: 'Linux i386'
description: 'Run in a Linux i386 container.'
inputs:
  nocache:
    default: false
    type: boolean
  run:
    required: true
runs:
  using: "composite"
  steps:
    - id: cache
      if: "!inputs.nocache"
      uses: actions/cache@v3
      with:
        path: |
          docker_linux_i386.tar
        key: docker_linux_i386-${{ hashFiles('.github/workflows/linux_i386.Dockerfile') }}

    - if: inputs.nocache || steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        docker build -t nim:linux_i386 - < .github/workflows/linux_i386.Dockerfile
        docker save nim:linux_i386 > docker_linux_i386.tar

    - run: |
        docker load -i docker_linux_i386.tar
        docker run --mount type=bind,src=`pwd`,dst=`pwd` -w `pwd` -t nim:linux_i386 ${{ inputs.run }}
      shell: bash
