name: csources

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

concurrency:
  group: csources
  # cancel-in-progress: true

on: workflow_call

jobs:
  cache-csources-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: cache-csources
        uses: actions/cache@v3
        with:
          path: |
            csources
            bin/nim_csources*
          key: csources-linux-amd64-${{ hashFiles('config/build_config.txt') }}

      - id: build_all_sh
        if: steps.cache-csources.outputs.cache-hit != 'true'
        run: sh build_all.sh

  cache-csources-linux-i386:
    runs-on: ubuntu-latest
    container: i386/ubuntu
    steps:
      - uses: actions/checkout@v3

      - id: cache-csources
        uses: actions/cache@v3
        with:
          path: |
            csources
            bin/nim_csources*
          key: csources-linux-i386-${{ hashFiles('config/build_config.txt') }}

      - id: build_all_sh
        if: steps.cache-csources.outputs.cache-hit != 'true'
        run: sh build_all.sh

  cache-csources-macos-amd64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - id: cache-csources
        uses: actions/cache@v3
        with:
          path: |
            csources
            bin/nim_csources*
          key: csources-macos-amd64-${{ hashFiles('config/build_config.txt') }}

      - id: build_all_sh
        if: steps.cache-csources.outputs.cache-hit != 'true'
        run: sh build_all.sh

  cache-csources-windows-amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - id: cache-csources
        uses: actions/cache@v3
        with:
          path: |
            csources
            bin\nim_csources*
          key: csources-windows-amd64-${{ hashFiles('config\build_config.txt') }}

      - id: build_all_bat
        if: steps.cache-csources.outputs.cache-hit != 'true'
        run: .\build_all.bat
