name: csources

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

concurrency:
  group: csources
  # cancel-in-progress: true

on:
  workflow_call:
    inputs:
      nocache:
        required: true
        default: false
        type: boolean

jobs:
  cache:
    runs-on: ${{ matrix.platform.buildHost }}
    strategy:
      matrix:
        platform:
          - buildHost: ubuntu-latest
            os: linux
            arch: amd64
            buildCmd: sh build_all.sh

          - buildHost: ubuntu-latest
            os: linux
            arch: i386
            runOnDocker: true
            dockerImage: docker_linux_i386.tar
            buildCmd: sh build_all.sh ucpu=i386

          - buildHost: macos-latest
            os: macos
            arch: amd64
            buildCmd: sh build_all.sh

          - buildHost: macos-latest
            os: openbsd
            osVer: '7.1'
            arch: amd64
            runOnVm: true
            buildCmd: sh build_all.sh

          - buildHost: macos-latest
            os: freebsd
            osVer: '12.2'
            arch: amd64
            runOnVm: true
            buildCmd: sh build_all.sh

          - buildHost: ubuntu-latest
            os: netbsd
            osVer: '9.2'
            arch: amd64
            runOnVm: true
            buildCmd: sh build_all.sh

          - buildHost: windows-latest
            os: windows
            arch: amd64
            buildCmd: .\build_all.bat

    steps:
      - uses: actions/checkout@v3

      - id: cache-csources
        uses: actions/cache@v3
        with:
          path: |
            csources
            bin/nim_csources*
          key: csources-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ hashFiles('config/build_config.txt') }}

      - id: build_all
        if: (!matrix.platform.runOnDocker && !matrix.platform.runOnVm) && (steps.cache-csources.outputs.cache-hit != 'true' || inputs.nocache)
        run: ${{ matrix.platform.buildCmd }}

      - id: build_all_with_docker
        if: matrix.platform.runOnDocker && (steps.cache-csources.outputs.cache-hit != 'true' || inputs.nocache)
        uses: ./.github/actions/linux_i386.yml
        run: ${{ matrix.platform.buildCmd }}

      - id: build_all_with_vm
        if: matrix.platform.runOnVm && (steps.cache-csources.outputs.cache-hit != 'true' || inputs.nocache)
        uses: cross-platform-actions/action@v0.6.2
        with:
          operating_system: ${{ matrix.platform.os }}
          version: ${{ matrix.platform.osVer }}
          shell: bash
          run: ${{ matrix.platform.buildCmd }}
